import { Client } from "@/types/client";

function isoOffsetDays(days: number) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
}

let historyCounter = 0;

function makeHistory(
  daysAgo: number,
  type: Client["history"][number]["type"],
  title: string,
  description?: string
) {
  historyCounter += 1;
  return {
    id: `${type}-${historyCounter}`,
    date: isoOffsetDays(-daysAgo),
    type,
    title,
    description,
  };
}

export const MOCK_CLIENTS: Client[] = [
  {
    id: "c-001",
    companyName: "Alem Trade Distribution",
    name: "Serik Abenov",
    whatsappNumber: "+77011234567",
    email: "serik@alemtrade.kz",
    city: "Kyzylorda",
    segment: "Wholesale Distributor",
    product: "Ultra Degreaser",
    priority: "high",
    assignedTo: "Ayan",
    status: "negotiating",
    messageTemplate: "neutral_push",
    sampleSentDate: isoOffsetDays(-14),
    followUpDate: isoOffsetDays(1),
    nextAction: "Дожать по цене и согласовать первую поставку",
    lastContactAt: isoOffsetDays(-2),
    estimatedMonthlyValue: 2400,
    notes: "Нужна более выгодная цена при объеме свыше 400 л в месяц.",
    createdAt: isoOffsetDays(-30),
    updatedAt: isoOffsetDays(-2),
    history: [
      makeHistory(14, "sample_sent", "Пробники отправлены", "Доставка подтверждена."),
      makeHistory(9, "whatsapp_followup", "Касание в WhatsApp", "Пробник получен на складе."),
      makeHistory(2, "meeting", "Звонок с закупками", "Запросили обновленное КП."),
    ],
  },
  {
    id: "c-002",
    companyName: "Nova Office Services",
    name: "Dana Ilyas",
    whatsappNumber: "+77022334455",
    email: "d.ilyas@novaoffice.kz",
    city: "Almaty",
    segment: "Facility Services",
    product: "Glass Cleaner Pro",
    status: "waiting-test",
    messageTemplate: "second_followup",
    priority: "medium",
    assignedTo: "Kamila",
    sampleSentDate: isoOffsetDays(-10),
    followUpDate: isoOffsetDays(3),
    nextAction: "Запросить финальный отзыв по тесту на объекте",
    lastContactAt: isoOffsetDays(-1),
    estimatedMonthlyValue: 1700,
    notes: "Пилот запущен на двух офисных объектах.",
    createdAt: isoOffsetDays(-21),
    updatedAt: isoOffsetDays(-1),
    history: [
      makeHistory(10, "sample_sent", "Пробники отправлены"),
      makeHistory(6, "whatsapp_followup", "Запросили обратную связь", "Первые отзывы положительные."),
      makeHistory(1, "note", "Вторая неделя теста", "Ждем данные по расходу."),
    ],
  },
  {
    id: "c-003",
    companyName: "QazFood Logistics",
    name: "Arman Zhalgas",
    whatsappNumber: "+77037778899",
    email: "arman@qazfoodlogistics.kz",
    city: "Shymkent",
    segment: "Food Logistics",
    product: "Sanitize Max",
    status: "sample",
    messageTemplate: "first_followup",
    priority: "high",
    assignedTo: "Ayan",
    sampleSentDate: isoOffsetDays(-7),
    followUpDate: isoOffsetDays(0),
    nextAction: "Уточнить результат теста и снять возражения",
    lastContactAt: isoOffsetDays(-5),
    estimatedMonthlyValue: 2100,
    notes: "Высокий потенциал при успешном прохождении HACCP-проверки.",
    createdAt: isoOffsetDays(-15),
    updatedAt: isoOffsetDays(-5),
    history: [
      makeHistory(7, "sample_sent", "Пробники отправлены"),
      makeHistory(5, "whatsapp_followup", "Первичное касание"),
    ],
  },
  {
    id: "c-004",
    companyName: "Capital Clean Group",
    name: "Aruzhan Nurgali",
    whatsappNumber: "+77049995544",
    email: "aruzhan@capitalclean.kz",
    city: "Astana",
    segment: "Cleaning Contractor",
    product: "Foam Hand Soap",
    priority: "high",
    assignedTo: "Madina",
    status: "won",
    messageTemplate: "post_deal_thanks",
    sampleSentDate: isoOffsetDays(-28),
    followUpDate: isoOffsetDays(14),
    nextAction: "Подготовить план расширения ассортимента",
    lastContactAt: isoOffsetDays(-1),
    estimatedMonthlyValue: 4600,
    notes: "Закрыт годовой рамочный контракт.",
    createdAt: isoOffsetDays(-45),
    updatedAt: isoOffsetDays(-1),
    history: [
      makeHistory(28, "sample_sent", "Пробники отправлены"),
      makeHistory(23, "meeting", "Очная демонстрация завершена"),
      makeHistory(3, "status_change", "Переведен в Сделку", "Контракт подписан."),
    ],
  },
  {
    id: "c-005",
    companyName: "Delta Retail Network",
    name: "Nurlan Bek",
    whatsappNumber: "+77056667788",
    email: "n.bek@deltaretail.kz",
    city: "Aktobe",
    segment: "Retail Chain",
    product: "Glass Cleaner Pro",
    status: "new",
    messageTemplate: "first_followup",
    priority: "medium",
    assignedTo: "Kamila",
    sampleSentDate: isoOffsetDays(-2),
    followUpDate: isoOffsetDays(5),
    nextAction: "Сделать первое касание после отправки пробника",
    lastContactAt: isoOffsetDays(-2),
    estimatedMonthlyValue: 1200,
    notes: "После отправки пробника касания еще не было.",
    createdAt: isoOffsetDays(-5),
    updatedAt: isoOffsetDays(-2),
    history: [makeHistory(2, "sample_sent", "Пробники отправлены")],
  },
  {
    id: "c-006",
    companyName: "Orda Hospitality Supplies",
    name: "Madina Sarsembayeva",
    whatsappNumber: "+77061112233",
    email: "madina@ordahospitality.kz",
    city: "Karagandy",
    segment: "Hospitality",
    product: "Ultra Degreaser",
    priority: "low",
    assignedTo: "Ayan",
    status: "lost",
    messageTemplate: "silent_final",
    sampleSentDate: isoOffsetDays(-33),
    followUpDate: isoOffsetDays(-9),
    nextAction: "Вернуться через месяц с новым оффером",
    lastContactAt: isoOffsetDays(-8),
    estimatedMonthlyValue: 0,
    notes: "Выбрали текущего поставщика из-за более длинной отсрочки.",
    createdAt: isoOffsetDays(-50),
    updatedAt: isoOffsetDays(-8),
    history: [
      makeHistory(33, "sample_sent", "Пробники отправлены"),
      makeHistory(12, "meeting", "Обсуждение цены", "Решение отложено до согласования с финансами."),
      makeHistory(8, "status_change", "Переведен в Отказ", "Ограничение по бюджету."),
    ],
  },
];
